<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ginkgo.ServerToolkit.Abstractions\Ginkgo.ServerToolkit.Abstractions.csproj" />
    <ProjectReference Include="..\Ginkgo.Application\Ginkgo.Application.csproj" />
    <ProjectReference Include="..\Ginkgo.Shared\Ginkgo.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
